version: '3.8'

services:
  postgres:
    image: postgresdb:2.0  # Используем ранее созданный образ
    container_name: postgres-container
    ports:
      - "5433:5432"
    restart: always
  redissessions:
    image: redissession:1.0  # Используем ранее созданный образ
    container_name: redis-container
    ports:
      - "6380:6379"
    restart: always