version: '3.8'

services:
  postgres:
    image: my-postgres-image  # Используем ранее созданный образ
    container_name: my-postgres-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./sql-scripts/:/docker-entrypoint-initdb.d/
    restart: always