services:
  postgres:
    image: ssodb:1.0  # Используем ранее созданный образ
    container_name: ssodb-container
    ports:
      - "5434:5432"
    restart: always
  redissessions:
    image: redissessiondb:1.0  # Используем ранее созданный образ
    container_name: redis-container
    ports:
      - "6380:6379"
    restart: always